### PR TITLE
I know I am sentimental, but...  

### PR DESCRIPTION
**Pull request by RobertDober**
as jim is not a common unix command (yet)....

let's rake it one

### CODE REVIEW

**Comment by x-itec** [comment]
excellent idea

**Comment by drbrain** [comment]
This won't work.

I'm unconvinced this should be committed.

**Comment by rdlugosz** [comment]
It is a nice sentiment but I think this would be better off in the aliases section of your dotfiles.

**Comment by RobertDober** [comment]
I understand any sentiment against this, and it might as a matter of fact not work if is not announced somewhere prominently and given my popularity in the community...
I guess it is part of my morning and I hope nobody feels too strong about this admitted abuse of a pull request.
That said I still would love the idea...

**Comment by drbrain** [comment]
I don't think it was abuse, but I will close it

**Comment by RobertDober** [comment]
and before I forget @Boris, thank you for your support (but for those who
know DS9: No, it's not linear)

On Fri, Mar 7, 2014 at 5:30 PM, Boris Köster notifications@github.comwrote:

> excellent idea
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/jimweirich/rake/pull/259#issuecomment-37040620
> .

## 

Ignorance is the curse of God; knowledge is the wing wherewith we fly to
heaven.
--William Shakespeare

**Pull request closed without merging**
