### PR TITLE
Refactor the show_tasks option code into function and replace

### PR DESCRIPTION
**Pull request by fables-tales**
There was very similar code in 3 places in this method, so I broke the similar code up into a function and replaced it in the 3 places it was used.

### CODE REVIEW

**Comment by fables-tales** [comment]
Weird, I ran that and got this output:

```
5 (refactor-tasks-options)$ ruby -Ilib/ bin/rake TESTOPTS="--seed=37587"
Run options: --seed=37587

# Running tests:

......................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished tests in 10.416596s, 42.0483 tests/s, 118.7528 assertions/s.

438 tests, 1237 assertions, 0 failures, 0 errors, 0 skips
6 (refactor-tasks-options)$ 

```

**Comment by fables-tales** [comment]
it also passed without using bin/rake but the systemwide rake.

ruby version: `ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.4.0]`

**Comment by jimweirich** [comment]
Yes, the Travis CI failure was related to the signal propagation code, which apparently only works on some systems.

**Comment by fables-tales** [comment]
Ok. Do I need to modify this code?

**Pull request merged**
