### PR TITLE
refactoring code convention

### PR DESCRIPTION
**Pull request by riseshia**
change code block style from {} to do end in 'lib/rake/clean.rb'

### CODE REVIEW

**Comment by drbrain** [comment]
This already matches Jim's block convention, so I don't think it should be changed.

**Comment by riseshia** [comment]
First of all, I apologized bothered you. but I have question. I'm just started to study 'rake' for understanding how it works. by the way, I found somewhere used 'do end' block and somewhere used '{}' block in codes. is there any reason to write that way? or is there a document written rules for code convention of this library?

**Comment by drbrain** [comment]
There isn't a document, but Jim documented his style here:

https://web.archive.org/web/20140221124509/http://onestepback.org/index.cgi/Tech/Ruby/BraceVsDoEnd.rdoc

**Comment by riseshia** [comment]
Thanks to links!

**Pull request closed without merging**
