### PR TITLE
Ignore duplicated task description

### PR DESCRIPTION
**Pull request by zhaocai**

### CODE REVIEW

**Comment by jimweirich** [comment]
I would like a explanation of why we need to protect agains duplicate "desc" comments. Is this something you run into in a real life situation?

**Comment by jimweirich** [comment]
I generally do something like this:

``` ruby
# Code that gets executed once:

desc "Description of a task"
task :a_task
```

with

``` ruby
# Code that gets executed multiple times

task :a_task => [new_dependencies] do
  new_actions
end
```

**Comment by zhaocai** [comment]
``` ruby
# Code that gets executed once:

desc "Description of a task"
task :a_task

# Code that gets executed multiple times

task :a_task => [new_dependencies] do
  new_actions
end
```

I know this and that is what I did before. However, when the `distribute` command is put into unknown `namespace` by user, it is not easy to determine the desc for `task "unknown_namespaceA:task_a"`,  `task "unknown_namespaceB:task_a"`, ...

**Comment by zhaocai** [comment]
any explanation is appreciated. Thanks.

**Comment by jimweirich** [comment]
My reason for disallowing the change is the effect it has on how I would describe "desc" to a user: "Add a description to a task, unless the task already has that description".  I did't like the "unless" part, I felt it made its semantics too complex.

But now as I write the above, it occurs to me I could say: "Add a unique description to a task" ... Hmmm, this sounds better ... let me think on this a bit.

**Comment by zhaocai** [comment]
Thanks for the answer. :+1:

**Comment by jimweirich** [comment]
Looked into the issue and decided the whole comment thing needs some cleanup work.  Added a new maintenance issue (#194) to address the problem.

**Pull request closed without merging**
