### PR TITLE
Don't include rake directory in the load path if it's a default gem

### PR DESCRIPTION
**Pull request by spastorino**
/cc @drbrain

### CODE REVIEW

**Comment by jimweirich** [comment]
What is the purpose of this pull request?  What are you trying to fix?

**Comment by drbrain** [comment]
I worked with @spastoino on this pull request.

When:
1. Rake is a default gem
2. RubyGems has been updated (lives in sitelibdir)
3. The rake tests are run without this patch

The `-I` causes the RubyGems shipped with rake to appear first in `$LOAD_PATH` so you can't use any new features or bug fixes from that RubyGems.

**Comment by drbrain** [comment]
Err, you can't use any new features from the upgraded RubyGems that lives in sitelibdir.

**Comment by spastorino** [comment]
@jimweirich sorry for not giving any explanation in the pull request. We chatted on IM with @drbrain about this so I just sent the PR without giving context.

But let me try to explain here ...
I was trying to run `rake test` on a project and I figured that because of rake test is adding `-I\"#{rake_lib_dir}\"` the wrong Rubygems installation was picked.

Rubygems bundled installation comes in /Users/santiago/.rubies/2.1.0/lib/ruby/2.1.0/lib/ruby/2.1.0/rubygems.rb and the newer version I've installed is placed here /Users/santiago/.rubies/2.1.0/lib/ruby/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems.rb.
When rake installation is the bundled one rake_lib_dir will be /Users/santiago/.rubies/2.1.0/lib/ruby/2.1.0 so rake test will place that dir first and the wrong Rubygems installation will be used.

Sorry about by bad english :(

**Pull request merged**
