### PR TITLE
stop defining exclude? method

### PR DESCRIPTION
**Pull request by vipulnsward**
1.stop defining exclude? method as it is get defined later
2. sort => sort! on new hash

### CODE REVIEW

**Comment by drbrain** [comment]
sort! may return nil, so I don't think it should be used.  We can't guarantee that the list won't already be sorted by some ruby implementation.

**Comment by vipulnsward** [comment]
oh, missed it, will update

**Comment by vipulnsward** [comment]
@drbrain updated.

**Comment by jimweirich** [comment]
Since there is no "exclude?" method in arrays, there is no need to specifically not define it (the MUST_NOT_DEFINE list is used to list array methods that should not be delegated to the underlying array implementation).

I don't see the need for this change.

**Comment by vipulnsward** [comment]
@jimweirich railties was throwing a warning so proposed the change. Also rake doesn't exclusively define anything special for `exclude?` so saw no harm in doing this.
ex: https://travis-ci.org/rails/rails/jobs/6351273

**Comment by jimweirich** [comment]
Ah! It is rails that is adding an exclude? method.

Perhaps we should rename our exclude? method to avoid name collision. I'm reopening this while I ponder.

Although exclude? is public, I don't imagine it is often called in user code. Hmmmm.

**Comment by jimweirich** [comment]
I renamed the FileList method that was in conflict with the monkey-patched rails method. That should solve the issue.

**Comment by vipulnsward** [comment]
Thanks!

**Pull request closed without merging**
