### PR TITLE
Jim planned to remove 1.8 support with Rake 10.2

### PR DESCRIPTION
**Pull request by zzak**
@drbrain I think this was a typo?

### CODE REVIEW

**Comment by drbrain** [comment]
No, with rake 2.1 based on commit history. See #247 and it's references.

**Comment by zzak** [comment]
@drbrain Sorry, I couldn't locate anything that specifically suggested a Rake 2.1 would ever be released. I thought Rake 11 was going to be the next canonical release. The only other commit I could find which was _somewhat_ related around the time of Jim dropping 1.8 was a785f1b.

**Comment by drbrain** [comment]
Ah, then the typo is the version (rake 10.2), not rake -> ruby, can you update?

**Comment by zzak** [comment]
@drbrain Updated description and branch.

**Comment by drbrain** [comment]
The patch seems to be the original? It should say "Rake 10.2"

**Comment by zzak** [comment]
@drbrain Oops, forgot to `git add`

**Pull request merged**
