### PR TITLE
Add :phony task

### PR DESCRIPTION
**Pull request by zenspider**
See http://blog.zenspider.com/2012/01/simulating-phony-in-rake.html for more info

### CODE REVIEW

**Comment by jimweirich** [comment]
Example use?  Test Cases?

**Comment by zenspider** [comment]
Example use is described in detail in the url above. I'll try to figure out how to test this.

**Comment by zenspider** [comment]
Test added... I had to dupe the :phony creation inside the test because of helper's setup method...

**Comment by damphyr** [comment]
Why not extend the DSL with phony to achieve the same end instead of requiring a  => :phony dependency?

So you'd have 

phony :isolate => [:whatever]

But I'm still not sure how you use :isolate tbh

**Comment by zenspider** [comment]
PING

**Comment by zenspider** [comment]
I'm tired of non-communication. I've released this in makerakeworkwell.

**Comment by jimweirich** [comment]
Catching up on the backlog, sorry for the long delay.

Added this as an optional require.  Use

```
require 'rake/phony'
```

in your Rakefile to enable.

I'm still not sure what value the isolate task provides in your example.  If you would care to elucidate, it would be appreciated.

**Pull request merged**
