### PR TITLE
Config tasks proposal

### PR DESCRIPTION
**Pull request by thinkerbot**
Developers often use rake to build project-specific command line tools, even with alternatives like Thor out there.  For these it would be nice to provide task configurations without ENV variables, and to be able to use a more standard 'task arg arg' syntax rather than 'task[arg,arg]'.

To do so I propose commits in this pull request, which adds a new tasc syntax for ConfigTasks.  For example here is a command line tool to write a greeting.  It uses args, configs, and illustrates that simple config types are automatically converted to appropriate objects; String, Integer, Float, and true/false (for flags and switches) are supported.

```
require 'rake'

desc "welcome a thing"
tasc :welcome, :thing, %{
  -m,--message [hello]  : A welcome message
  -n [1]                : Number of times to repeat
} do |config, args|
  config.n.times do 
    puts "#{config.message} #{args.thing}"
  end
end
```

These tasks may be invoked using the current syntax. 

```
% rake welcome[world]
hello world
% rake welcome[--message,goodnight,-n,3,moon]
goodnight moon
goodnight moon
goodnight moon
```

Alternatively, the first commit in this request adds a new command line syntax whereby args after a '--' are re-written into the current syntax.  For example:

```
% rake -- welcome world
hello world
% rake -- welcome --message goodnight -n 3 moon
goodnight moon
goodnight moon
goodnight moon
% rake -- welcome --help
Usage: rake -- welcome [options] object
    -m, --message [hello]            A welcome message
    -n [1]                           Number of times to repeat
    -h, --help                       Display this help message.
```

The new syntax and ConfigTask class do not interfere with any of the current functionality AFAIK, and does not add dependencies. If you want I can clean up these commits into two separate pulls -- one for the 'option' syntax and one for ConfigTask.  In addition, I recognize ConfigTask could use a little more internal documentation which I will add if you intend to pull in these changes.

Thanks!  Hope you like the proposal!

### CODE REVIEW

**Comment by qrush** [comment]
This is awesome. Please merge!

**Comment by sikachu** [comment]
I really wish that this got merged into the core. Way more superior way than having to do `rake welcome[--message,goodnight,-n,3,moon]` or using the environment variable.

**Comment by veryhappythings** [comment]
As a rather casual user of rake, I think that new users would find the -- in `rake -- welcome world` pretty difficult to grasp.  Much better than the current syntax though!

**Comment by qrush** [comment]
@veryhappythings: The [daemons](http://rubygems.org/gems/daemons) gem has a similar pattern if you want to pass custom arguments:

`daemons run -- -s blah`

And "-s blah" would get passed along. I think it works pretty well. In any case I think this is better than doing environment variables or the "bracket" syntax which doesn't work in many shells.

**Comment by lukaszkorecki** [comment]
Not entirely convinced about `--` but still - **huge** improvement comparing to what we have now.

+1

**Comment by veryhappythings** [comment]
@qrush: Yeah, I've seen it used in several command line tools in the format `rake welcome -- world` (as opposed to `rake -- welcome world` as originally written) - I think that would make sense.

**Comment by jimweirich** [comment]
Interesting proposal, and you seem to have a bit of support.

I do like the -- syntax above (but not so wild about the tasc thing).

I want to take this slow, we've gone through several iterations of task arguments and I want to make sure what ever we introduce will wear well with age.

So, I guess I'm considering it.

**Comment by kronn** [comment]
I like the idea in general but I would prefer calling it `config_task` or something similar in the Rakefile. `tasc` looks like a typo too me, though I can see the intention there.

Is it possible to have the standard `task` accept this third argument with options? That would be ideal I think.

**Comment by kronn** [comment]
@thinkerbot I would be happy with a new method. The name should be clearly different, then. `cmd` also is closer to the shell. :)

**Comment by kagminjeong** [comment]
The brackets syntax is ugly, brackets are special for the shell and must be escaped, using commas to separate arguments will wreak havoc with arguments that contain commas necessitating yet another escaping scheme.

The second syntax is pretty good. -- should be optional if there are no arguments so that `rake task` continues to work. After a transition period of 1-2 years rake arguments may be required to appear before the first task name if there is no --, such that -- would not need to be specified at all.

However, I wonder what the ultimate utility is of this proposal. It is already possible to say `rake task arg=value` with both arg and value in lower case. Is there anything this proposal permits that cannot already be done?

**Comment by tapajos** [comment]
Please, merge it.

**Comment by twe4ked** [comment]
> The new syntax and ConfigTask class do not interfere with any of the current functionality AFAIK, and does not add dependencies.

I don't see a reason this shouldn't be merged.

**Comment by jimweirich** [comment]
There seems to be a real desire on some to be able to write procedural-like tasks, and this desire manifests in calls for better arguments to tasks and tasks that can be invoked multiple times.  

It seems to me that we already have a pretty good tool for writing these and its called methods.  Perhaps all we need is a place to put regular methods that can be invoked from the command line (like a task), arrange for it to easily pick up arguments and then decide how it ties into the task dependency system.

I'm not going to approve this pull request as it stands because I feel it only partially addresses the issues I see being requested.  But I'll leave it open for the moment so that the discussion can continue.

**Comment by ixti** [comment]
Just a humble proposal to have this feature closer to DSL we have now:

``` ruby
desc "Task description"
opts :count, "-n", :required => true, :desc => "Arg description"
opts :message, "-m", "--message", :default => "hi", :desc => "More description"
taks :foobar do |t, args|
  puts "#{args[:message}" * args[:count]
end
```

**Comment by jimweirich** [comment]
No progress on this ... closing.

**Pull request closed without merging**
